"""make categories user-specific

Revision ID: 53fc6afb1372
Revises: cf6ece4355fe
Create Date: 2025-11-26 20:10:29.585026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53fc6afb1372'
down_revision = 'cf6ece4355fe'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])

    conn = op.get_bind()
    conn.execute(sa.text("UPDATE categories SET user_id = 1 WHERE user_id IS NULL"))

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.Integer(), nullable=False)
        batch_op.create_unique_constraint(
            "uq_category_user_name", ["user_id", "name"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_constraint("uq_category_user_name", type_="unique")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
